import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css'; // Importa los estilos de FontAwesome
import '@/app/lib/fontawesome'; // Configuración personalizada de FontAwesome

//Providers
import ThemeProvider from "./providers/ThemeProvider";
import { ThemeContextProvider } from "./context/ThemeContext";
import  Navbar  from "@/app/ui/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ThemeContextProvider>
          <ThemeProvider>
            <div className="container" >
            <Navbar/>
            
            {children}
            </div>
            
            </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
