import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css'; // Importa los estilos de FontAwesome
import '@/app/lib/fontawesome'; // Configuración personalizada de FontAwesome

//Providers
import {ThemeProvider} from "./providers/ThemeProvider";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ModeToggle } from "./ui/ModeToggle/ModeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <SidebarProvider>
                <AppSidebar />
                <div className="flex-1">   
                  {children}
                </div>

              </SidebarProvider>

          </ThemeProvider>
      </body>
    </html>
  );
}
